name: Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t jordangpt:latest .

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Tag Docker image
        run: docker tag jordangpt:latest gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest

      - name: Push Docker image to GCR
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy jordangpt --image gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest --platform managed --region us-east1
