# name: Deploy to Google Cloud Run

# on:
#   push:
#     branches:
#       - main # Trigger the workflow on push to the main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       # - name: Build Docker image
#       #   run: docker build -t jordangpt:latest .

#       - name: Setup gcloud CLI
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           version: "latest"
#           project_id: ${{ secrets.PROJECT_ID }}

#       - name: Authenticate with gcloud
#         uses: google-github-actions/auth@v0.4.0
#         with:
#           credentials: ${{ secrets.GCLOUD_AUTH }}

#       - name: Authenticate with Google Cloud
#         run: echo ${{ secrets.GCLOUD_AUTH }} | gcloud auth activate-service-account --key-file=-

#       - name: Configure gcloud
#         run: gcloud config set project ${{ secrets.PROJECT_ID }}

#       - name: Tag Docker image
#         run: docker tag jordangpt:latest gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest

#       - name: Push Docker image to Google Container Registry
#         run: docker push gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest

#       - name: Deploy to Google Cloud Run
#         run: gcloud run deploy jordangpt --image gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest --platform managed

name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Adjust this if you want to run the action on a different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_AUTH }}

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy jordangpt --image gcr.io/${{ secrets.PROJECT_ID }}/jordangpt:latest --platform managed
