name: Pull from ECR, Run, and Deploy to GitHub Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1

    - name: Pull Docker Image
      run: docker pull ${{ secrets.AWS_ACCESS_KEY }}.dkr.ecr.us-east-1.amazonaws.com/jordangpt:latest

    - name: Run Docker Image to Generate Static Content
      run: |
        docker run --name mycontainer ***.dkr.ecr.us-east-1.amazonaws.com/jordangpt:latest
        docker cp mycontainer:/path/in/container/to/output ./output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
