jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Pull Docker Image
      run: |
        docker pull ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.us-east-1.amazonaws.com/jordangpt:latest
    - name: Run Docker Image
      run: |
        docker run -it -p 7860:7860 ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.us-east-1.amazonaws.com/jordangpt:latest
